### ISSUE TITLE
ChangedNotification for calculated properties

### ISSUE THREAD

**Issue by D0ctorWh0** [Maxumka/NOB#2]
Would be great to generate change notifications for calculated properties. For example for class

```
[ViewModel]
public partial class Model
{
    [Property]
    public int x;
    [Property]
    public int y;
    public int Z => _x * _y;
}
```
would be great to have X and Y generated properties have not only

OnPropertyChanged(nameof(PropertyX));

but also

OnPropertyChanged(nameof(Z));

**Comment by Maxumka** [comment]
Hi, D0ctorWh0.
In last commit(161903d853008db05d8c296e8eea29ace1d839a4), I add support calculated properties
